### ISSUE TITLE
Configurations of the models 

### ISSUE THREAD

**Issue by PastelBelem8** [salesforce/summary-of-a-haystack#2]
Hello, 

Thank you so much for this work! I was wondering if the authors could share what hyperparameters were used to evaluate and generate the summaries. Did you simply use the default OpenAI Chat completion hyperparameters (temperature = 1, top_p = 1) or were other parameters used?

**Comment by tingofurro** [comment]
Hey @PastelBelem8, good question.

We used default parameters for all models (temperature = 1, top_p = 1).
It would be interesting to see what effect the generation parameters would have on the results, but we have not explored this yet!
Happy to hear your thoughts,

Philippe
