### ISSUE TITLE
Code & Data for Automatic Metric Validation

### ISSUE THREAD

**Issue by HarlynDN** [salesforce/summary-of-a-haystack#3]
Hi,

Thank you for this awesome work! Are you planning to release the human-annotated summaries and evaluation script to run the experiments in Table 1 of your paper? I am interested in further testing additional models and evaluation strategies.

**Comment by tingofurro** [comment]
Hello @HarlynDN and thank you for your message.

I've just pushed to the repo our annotation data (200 samples), and the accompanying notebook (Eval_Benchmarking.ipynb) that should help reproduce the experiment.

Excited to see what you cook up to try to improve the eval strategies :) 

Philippe

**Comment by HarlynDN** [comment]
Thank you for the update :)
